version: "3.9"
services:
  web:
    build: .
    ports:
      - "8085:8085" 
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=DEBUG
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
        - redis

  redis:
    image: "redis:alpine"

