name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: python3-slim-buster
    steps:
      # Step 1
      - uses: actions/checkout@v2
     

  continuous-deployment:
    runs-on: python3-slim-buster
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name riva \
            --deployment-group-name github_action \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ Riva_client }},commitId=${{cb2a4030c332e6d6a8f5b2cde8be533ebd695bb0 }}
