name: CI/CD Pipeline2
on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: self-hosted
    steps:
      # Step 1
      - uses: actions/checkout@v2

  continuous-deployment:
    runs-on: self-hosted
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'  
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Create CodeDeploy Deployment
      #  id: deploy
        run: |
              if [[ -f "~/anubhav/Riva_client" ]]
              then
                  rm -rf ~/anubhav/Riva_client
              fi
              cd ~/anubhav/
              git clone https://github.com/aniforverizon/Riva_client.git
              cd Riva_client
              docker container stop $(docker container ls -aq)
              docker rm -f $(docker ps -aq) 
              docker rmi -f heet
              docker-compose down
              docker build -t heet .
              docker-compose up -d
           #      --application-name riva \
       #     --deployment-group-name github_action \
      #      --deployment-config-name CodeDeployDefault.OneAtATime \
      #      --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
